### DISCUSSION TITLE
No output from flake8 on Windows

### DISCUSSION THREAD

**Discussion by deadkex** [akaihola/darker#368] [Q&A] [answered]
Hi!
I am using darker in combination with pre-commit and the linters i would like to use are pylint and flake8.
The problem is that i cannot get any output from flake8, on the other hand pylint works as expected.
If you take below config and `pre-commit run --file test.py`, you can see that flake8 is actually running and reporting violations, but darker is not showing them. I also tried committing larger files with lots of changes or explicitly adding violations as changes.

python: 3.8.10
darker: 1.5.0
pre-commit: 2.19.0
flake8: 4.0.1
black: 22.3.0

.pre-commit-config.yaml
```
default_language_version:
    python: python3

repos:
-   repo: local
    hooks:
    -   id: darker
        name: darker
        entry: darker
        language: system
        types: [python]
        args: [
            "-L flake8 -v"
        ]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
```

pyproject.toml
```
[tool.darker]
src = ["./"]
revision = ":PRE-COMMIT:"
diff = false
check = true
isort = false
# lint = [
#     "flake8"
# ]

[tool.black]
target-version = ["py38"]
include = '\.py?$'
```

test.py
```
try:
    pass
except:
    pass
```
