### DISCUSSION TITLE
Darker doesn't work with github action

### DISCUSSION THREAD

**Discussion by Asuskf** [akaihola/darker#413] [Q&A] [answered]
Configuration: 
```yaml
test_pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-python@v4
      - uses: akaihola/darker@1.5.1
```

Error:
```python
TypeError: gen_python_files() got an unexpected keyword argument 'gitignore'
```

![image](https://user-images.githubusercontent.com/36687747/207107336-024c4f86-1f9b-4650-9446-270db51bc87d.png)
