### ISSUE TITLE
Not ignoring files even though it is excluded in Black config

### ISSUE THREAD

**Issue by roniemartinez** [akaihola/darker#146]
So here's a sample config for Black and `setup.py` is ignored by Black when you run it.

```toml
[tool.black]
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/setup.py
```

However, darker is not respecting this configuration and still reformats `setup.py`

Additional detail: darker is set in Pycharm's File Watcher so it keeps reformatting excluded files.
