### ISSUE TITLE
Add option to add linters (flake8, mypy, etc.) in the GH Action

### ISSUE THREAD

**Issue by roniemartinez** [akaihola/darker#281]
There is no other way to add the supported linters other than creating separate steps to install.

**Comment by akaihola** [comment]
This would require installing all the linter packages in the action image. I've considered that, and maybe that's indeed a good approach.

**Comment by akaihola** [comment]
I believe `pylint` needs to be installed and run from the same Python environment as the source code it inspects. So the user's project and its dependencies need to be `pip install`ed in the action container. For example the [GitHub Action for pylint](https://github.com/marketplace/actions/github-action-for-pylint) by @cclauss seems to allow the user to specify commands to run before `pylint` is invoked:
>Each time that new code is pushed into your repo, you can have a [pylint](https://docs.pylint.org/) command automatically run.
>```python
>args = "pip install -r requirements.txt ; pylint **/*.py"
>```
>The `args` parameter should probably have to be modified to suit each project's needs.
>
>For instance, Pylint will raise errors like `E0401: Unable to import 'requests' (import-error)` if a project's imports have not been `pip install`ed. It is therefor useful to place a `pip` or `pipenv` command before the `pylint` command separated with a semicolon (`;`). Some examples:
>
>```python
>args = "pip install -r requirements.txt ; pylint **/*.py" # for projects that use requirements.txt files
>args = "pip install . ; pylint **/*.py" # for projects that put their dependencies in setup.py
>```

**Comment by cclauss** [comment]
#310

**Comment by cclauss** [comment]
The comments above seem to lean towards making an "action image" so I created #310 to show that lots of testing tools can be quickly installed and run on a base action image that that approach is easier to run on multiple OSes and Python versions as well as being more resilient to change than a frozen custom image will be.

**Comment by roniemartinez** [comment]
> I believe pylint needs to be installed and run from the same Python environment as the source code it inspects. So the user's project and its dependencies need to be pip installed in the action container.

This only applies to `pylint`.

As for us, we use `flake8` as the linter with `darker` and it does not require us to install the project dependencies. This comes in handy for us because we have a lot of dependencies which takes a long time to install. This saves us time spent in Github Actions.

**Comment by cclauss** [comment]
#310 25 sec != long time

**Comment by akaihola** [comment]
>I created https://github.com/akaihola/darker/pull/310 to show that lots of testing tools can be quickly installed and run on a base action image

In #310, we added extra checks for Darker's own action workflow.

If I've understood correctly, @roniemartinez wants the [custom action](https://docs.github.com/en/actions/creating-actions/about-custom-actions) defined by the Darker repository to be able to run not only Black and `isort`, but also linters, and filter their output to only those concerning modified lines in the source code.

To apply the learnings of #310 to the custom action, I assume we need to
- define extra inputs in [`action.yml`](https://github.com/akaihola/darker/blob/8a1835c952b9743ea5cb6d40d23eb9c6458e7828/action.yml#L5-L24) which accept a list of extra reformatters and linters which Darker should run in the action, and
- install corresponding extra dependencies in [`action/main.py`](https://github.com/akaihola/darker/blob/8a1835c952b9743ea5cb6d40d23eb9c6458e7828/action/main.py#L19-L27) before running Darker.

Also, if we want the custom action to be able to run tools like `pyupgrade`, `bandit`, `safety` and `codespell` and filter their outputs to modified lines only, we need to either make sure they output standard linter format (similar to `pylint`, `mypy` and `flake8`), or to teach Darker how to parse their output.

Is this an accurate summary of what this issue is about?

**Comment by roniemartinez** [comment]
Yes, @akaihola that is correct.

We want to include extra linters, etc. and have it handled by darker instead of defining initial steps. Just to make it a little more clearer, we want to remove the extra steps that user define for themselves in order to use linters.

```yaml
      - name: Install flake8
        run: pip3 install flake8

      # insert extra steps here

      - uses: akaihola/darker@1.4.0
        with:
          options: "...  --lint flake8 ..."
```

Instead, we want it to be simpler and optionally remove defining `--lint`.

```yaml
      - uses: akaihola/darker@1.4.0
        with:
          linters: [flake8, ...]  # or extras
```

**Comment by akaihola** [comment]
@roniemartinez, judging from [Metadata syntax for GitHub Actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) documentation, as well as the [`github-action.json` schema](https://json.schemastore.org/github-action.json), values for inputs can only be strings, not lists of strings. It actually makes sense since they end up as values of environment variables for the composite action script.

So either linters must be expressed as e.g. a comma-separated list:
```yaml
      - uses: akaihola/darker@1.4.0
        with:
          linters: flake8,mypy,pylint
```
or each linter should get their own input:
```yaml
      - uses: akaihola/darker@1.4.0
        with:
          flake8: true
          mypy: true
          pylint: true
```

What do you think?

**Comment by roniemartinez** [comment]
@akaihola 
The first option looks easier to extend. But I am still good with the second option.

**Comment by akaihola** [comment]
>first option looks easier to extend

Would there be any risk in allowing any strings to appear in the `linters:` comma-separated list, and just `pip install`ing them all and adding each of them as a `--lint <linter>` argument to Darker?

So 
```yaml
      - uses: akaihola/darker@1.4.0
        with:
          linters: pylint,my-super-linter
```

would make sure these are executed in `action/main.py`:
```bash
pip install pylint my-super-linter
darker --lint pylint --lint my-super-linter <other options> <path>
```

This way the GitHub Custom Action wouldn't need any modifications even if support for more linters is added to Darker – as long as the package name and command name of the linter are the same.

**Comment by roniemartinez** [comment]
> Would there be any risk in allowing any strings to appear in the linters: comma-separated list, and just pip installing them all and adding each of them as a --lint <linter> argument to Darker?

The only risk that I can see is when someone misspells the package name and ending up downloading a name-squatting package. That's probably a big security issue. 🤔

**Comment by akaihola** [comment]
>misspells the package name and ending up downloading a name-squatting package

...and that could happen in an Open Source project by someone sneaking the "typo" in a pull request, and the workflow running either after a maintainer acknowledged the request to run it, or automatically if the malicious user is a collaborator on the project.

So I guess it's good if we still validate the items in the value of `linters:`.

Another question that occurred to me is whether it's ok to not allow passing arguments to the linters. Darker would accept e.g. `darker --lint "pylint --opt1 --opt2" .` but if we want to allow that, there needs to be some clever syntax to define both the package name and the command line for each linter.

**Comment by akaihola** [comment]
A couple of thing still. Maybe these are not essential for the first iteration of linter support, but let's make sure the design will allow for these to be added without breaking backwards compatibility.

### Pinning

Should we allow pinning linter versions?

For example:
```yaml
      - uses: akaihola/darker@1.5.0
        with:
          lint: pylint==2.12.2, flake8=3.9.2
```

### Plugins

There seem to be a few quite nice `flake8` plugins like [flake8-2020](https://pypi.org/project/flake8-2020/), [flake8-bugbear](https://pypi.org/project/flake8-bugbear/), [flake8-spellcheck](https://pypi.org/project/flake8-spellcheck/), and [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/). The proposed syntax for linters wouldn't allow adding those. Maybe we need another option for installing extra packages:

```yaml
      - uses: akaihola/darker@1.5.0
        with:
          lint: pylint==2.12.2, flake8=3.9.2
          extra-packages: flake8-2020==1.6.1, flake8-bugbear==22.1.11
```
But the risk of typos and PyPI name-squatting emerges again, so maybe these should be checked against a whitelist as well?
