### ISSUE TITLE
Allow pinning linter packages in the GitHub Action

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#337]
To keep GitHub workflows stable, users may want to pin both Darker and linter packages to fixed versions when using the GitHub Action. Darker can already be pinned using the `version:` option, but linter pinning wasn't yet added in #313.

# Alternatives for the syntax

In these examples, Pylint is pinned but the newest version of Flake8 is to be installed.

## Embed versions in `lint:` option
In this alternative, items in `lint:` need to be validated and passed to `pip install`, and command names without the version are needed for the Darker command line `--lint` options. For linters with no version number, the newest version on PyPI would be installed:

`.github/workflows/darker.yml`:
```yaml
      - uses: akaihola/darker@1.5.0
        with:
          lint: pylint==2.12.2, flake8
```

## A separate `constraints:` option
Here, versions of packages are provided in a separate `constraints:` option. If a linter is omitted from `constraints`, the newest version would be installed.

The use of this option could extend beyond just linters. We could even deprecate the `version:` option and guide users to use `constraints: darker==1.5.0` instead. And this could also solve the missing `isort` version pinning feature.

`.github/workflows/darker.yml`:
```yaml
      - uses: akaihola/darker@1.5.0
        with:
          lint: pylint, flake8
          constraints: pylint==2.12.2
```

## Constraints in a text file
We could also require the user to provide constraints in a text file and point to it in a `constraints-file:` option:

`.github/workflows/darker.yml`:
```yaml
      - uses: akaihola/darker@1.5.0
        with:
          lint: pylint, flake8
          constraints-file: .github/workflows/darker-lint-constraints.txt
```

`.github/workflows/darker-lint-contstraints.txt`:
```
pylint==2.12.2
```

# Considerations

- Is the Pip constraints feature well enough known, or would it be better to use the name `versions:` instead of `constraints:`?
