### ISSUE TITLE
When using `pre-commit` and `color = true`, linter output is missing spaces

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#387]
When using `color = true` the output is missing spaces:
```
test.py:155:5:E722donotusebare'except'
test.py:167:5:E303toomanyblanklines(5)
```

(_Originally posted by @deadkex in https://github.com/akaihola/darker/issues/378#issuecomment-1230181194_)

This may be specific only to Windows and only to IDEs like PyCharm and IntelliJ. More testing needed to confirm that.

**Comment by akaihola** [comment]
@deadkex, could you please specify
- your operating system and version,
- Python version,
- Darker version,
- Pygments version,
- your `pyproject.toml` contents, and
- the Darker command line?

Thanks!

**Comment by deadkex** [comment]
- Windows 10 Pro 21H2
- Python 3.8.10
- Branch https://github.com/akaihola/darker.git@linter-output-full-path
- Pygments 2.13.0
- pyproject.toml:
```
[tool.darker]
src = [
    "./"
]
revision = ":PRE-COMMIT:"
diff = false
check = true
isort = false
color = true

lint = [
    """
    pylint
        --rcfile=tools/pylintrc.conf
    """,
    """
    flake8
        --ignore=E501,F841,E722
        --max-line-length=80
    """
]
log_level = "INFO"

[tool.black]
target-version = ["py38"]
include = '\.py?$'
```
- i ran darker via pre-commit
- .pre-commit-config.yaml:
```
default_language_version:
    python: python3

repos:
-   repo: local
    hooks:
    -   id: darker
        name: darker
        entry: darker
        language: system
        types: [python]
```
