### ISSUE TITLE
Configuration file(s)

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#49]
Like with Black, it would be convenient to be able to set Darker's options not only on the command line but also in per-repository configuration files.

>I was also thinking in a config file (pyproject.toml at the root of the repo?) having the ability to >give a revision to be used by default. But +1.
_Originally posted by @Carreau in https://github.com/akaihola/darker/pull/43#issuecomment-670788073_

- [ ] highlighting for TOML configuration dump (using code in #57, merge that first)

**Comment by akaihola** [comment]
We'll need to settle for (1) the location(s) of Darker configuration, and (2) the format of it.

My number one proposal would be `pyproject.toml` and a `[tool.darker]` section in it. This is what both Black and isort already support, and seems to be becoming the standard.

Mapping command line options to directly to `pyproject.toml` would suggest a format like this (with default values shown here):
```toml
[tool.darker]
src = []
revision = "HEAD"
diff = false
check = false
isort = false
lint = []
log_level = "WARNING"
```
So if I'd like to make these options default:
```bash
darker -vv -r master --check --diff --isort -L flake8 -L mypy -L pylint -L cov_to_lint.py src  
```
I would put this in `pyproject.toml`:
```toml
[tool.darker]
src = [ "src",]
revision = "master"
diff = true
check = true
isort = true
lint = [ "flake8", "mypy", "pylint", "cov_to_lint.py",]
log_level = "DEBUG"
```
