### ISSUE TITLE
`pyproject.toml` options with hyphens are ignored

### ISSUE THREAD

**Issue by dwt** [akaihola/darker#502]
**Describe the bug**
It seems that Darker ignores config options in `pyproject.toml` if they are spelled using hyphens instead of underscores.

**To Reproduce**
I have configuration for a Darker pre-commit hook like this:

```yaml
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization ]

```

and a `pyproject.toml` like this:

```toml
[tool.darker]
line-length = 120
skip-string-normalization = true
```

However running `pre-commit` it did not honor the line length setting in `pyproject.toml`.

Reading the documentation and other bug reports here, it seems this ought to work.

Is this an issue in `pre-commit`, perhaps something to do with the fact that the pre-commit hook acts directly on the files that are part of the commit and therefore ignores the `pyproject.toml`?

Or is this a bug in Darker that I need to file there?

Changing the pre-commit hook to include the setting does seem to be a workaround. I.e.:

```yaml
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization , --line-length=120 ]
```

**Expected behavior**
Darker should honor the config option `line-length = 120` in the pyproject.toml

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version 3.10.12
 - Git version 2.39.2 (Apple Git-143)
 - Darker version 1.7.1
 - Black version black, 22.8.0 (compiled: yes)
 - other reformatter and linter versions ruff==0.0.272

**Comment by dwt** [comment]
This is a continuation from https://github.com/pre-commit/pre-commit/issues/2909 where I asked first, as I assumed this might be a feature of pre-commit that was misunderstanding.

**Comment by akaihola** [comment]
Thanks @dwt for the report, I was just able to reproduce this and will dig deeper now to find the cause.

**Comment by akaihola** [comment]
Actually @dwt I'm not sure if I really reproduced it.

Could you add verbosity to your configuration:
```yaml
  - repo: https://github.com/akaihola/darker
    rev: 1.7.1
    hooks:
      - id: darker
        args: [ --skip-string-normalization, -vv ]
```

and run `pre-commit` again.

Do you see the `line-length` setting included in debug output for both the `# Effective configuration:` section and the `# Configuration options which differ from defaults:` section?

If you do see it, the configuration is read correctly from `pyproject.toml`. If you don't see it, please double check your `pyproject.toml` – I do see the setting if I add it.

I can continue with the investigation after you've tried this out.
