### ISSUE TITLE
Github action: Doesn't correctly compute the commit_range when using `pull_request_target`

### ISSUE THREAD

**Issue by tru** [akaihola/darker#517]
**Describe the bug**
If the action is triggered on `pull_request_target` instead of `pull_request` the auto-detection doesn't work.

**To Reproduce**

here is my action file:

```
name: "Check Python Formatting"
on:
  pull_request_target:
    # run on .py
    paths:
      - '**.py'

jobs:
  python_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.py'

      - name: "Listed files"
        run: |
          echo "Formatting files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Python Formatting
        uses: akaihola/darker@1.7.2
        with:
          options: "--check --diff --color"
          version: "~=1.7.2"
          src: "${{ steps.changed-files.outputs.all_changed_files }}"
```

This doesn't work unless I change to `pull_request` on the third line.

**Expected behavior**
It should work for this.
