### ISSUE TITLE
Wrong parsing of pre-commit output (with ruff formatter)

### ISSUE THREAD

**Issue by benyamingg** [akaihola/darker#822]
**Describe the bug**

When using Darker as a pre-commit hook, its non-error output is sometimes interpreted by pre-commit as an error.

**To Reproduce**

Here is my `.pre-commit-config.yaml`:

```yaml
- repo: https://github.com/akaihola/darker
  rev: ce564e262ffe1573925cf4113ebcf0157e0274ae
  hooks:
    - id: darker
      args:
          - --formatter=ruff
          - --revision=origin/next-release
```

When I make a commit, pre-commit outputs the following:

```
darker...................................................................Failed
- hook id: darker
- files were modified by this hook
<here I would expect the list of files, but this is the full output>
```

So, the commit is marked as failed—even though the hook successfully formats the files.

If I then commit again, since no files are modified the second time, the hook passes without issues.

Allso, adding `--diff` parameter to the pre-commit config helps to fix the issue -- but than it doesn't prints the affected files list

**Environment (please complete the following information):**

- OS: macOS
- Python version: 3.11
- Darker version: latest from Git (to support the --formatter feature)
- Ruff version: 0.11.2
